### ISSUE TITLE
Summary of background and project ideas

### ISSUE THREAD

**Issue by holeung** [AMLResearchProject/AML-ALL-Drug-Discovery#11]
**Is your feature proposal related to a problem? Please describe.**
Lack of big picture focus and specific project ideas.

**Describe the solution you'd like to submit**
Background for those new to AML and drug discovery research. Specific proposals relevant to AML that fall into my domain expertise.

**Describe alternatives you've considered**
Open to additional suggestions about project ideas, but they should be backed up with experience on proposed approach, and eventually, a practical plan for implementation.

**Additional context**
[AML drug discovery background.pdf](https://github.com/AMLResearchProject/AML-ALL-Drug-Discovery/files/2907522/AML.drug.discovery.background.pdf)

**Comment by AdamMiltonBarker** [comment]
Thanks Ho. I will take you through submitting a pull request on Skype with Estela this week.

**Comment by AdamMiltonBarker** [comment]
Hi Ho, I have added your information on your behalf. Parts have been used on the primary README and an article has been put in the Articles section for section. Thanks for contributing!

https://github.com/AMLResearchProject/AML-ALL-Drug-Discovery/blob/master/README.md

https://github.com/AMLResearchProject/AML-ALL-Drug-Discovery/blob/master/Articles/AML-Drug-Discovery-Background.md
