### ISSUE TITLE
Targeting the immunomodulatory target, STING

### ISSUE THREAD

**Issue by holeung** [AMLResearchProject/AML-ALL-Drug-Discovery#12]
**Is your feature proposal related to a problem? Please describe.**
No

**Describe the solution you'd like to submit**
Development of a research proposal to identify new small molecule activators of the immunomodulatory drug target, STING

**Describe alternatives you've considered**

**Additional context**
Identified a set of 450,000 molecules for further analysis as potential STING activators.

[STING activators.pdf](https://github.com/AMLResearchProject/AML-ALL-Drug-Discovery/files/3001011/STING.activators.pdf)

**Comment by AdamMiltonBarker** [comment]
Hi Ho, I have added your article on your behalf to the repo.

https://github.com/AMLResearchProject/AML-ALL-Drug-Discovery/blob/master/Articles/Identifying-New-STING-Activators.md
